"""Tone Master Pro 1.8 계열용 추천 모델 카탈로그.

표시 모델명과 컨트롤명은 Fender Tone Master Pro Model Guide Rev. J를
기준으로 정리했다. 목표 벡터는 공식 측정값이 아니라 이 앱이 사용하는
휴리스틱 값이며, 공개되지 않은 내부 모델 ID는 사용하지 않는다.
"""

from __future__ import annotations


APP_VERSION = "0.0.03"
TARGET_FIRMWARE = "1.8.58"
MODEL_GUIDE_REVISION = "Rev. J (2026-07)"
BUILD_DATE = "2026-09-03"


# 앱 내부의 변경 기록 화면과 배포 문서가 함께 사용하는 단일 원본이다.
# 이후 패치는 0.0.02, 0.0.03처럼 한 단계씩 올리고 최신 항목을 맨 위에 둔다.
CHANGELOG: list[dict] = [
    {
        "version": "0.0.03",
        "date": BUILD_DATE,
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "별도 결과 카테고리에 시간대별 코드 보이싱(실험) 분석 추가",
            "guitar stem의 코드명·구성음·베이스/역위·음역·간격·신뢰도 표시",
            "오디오에서 검출한 운지로 오인하지 않도록 일반적인 바레 운지를 '연주 후보'로 분리 표시",
            "앱 실행 로그를 포터블 data/logs 폴더에 날짜별 UTF-8 파일로 영구 기록",
            "개발자 탭에서 소스·세션/일별 로그·한영 이력·환경 진단을 DebugBundle ZIP으로 내보내기",
            "다른 Windows PC에서 실행과 개발을 이어갈 전체 소스·빌드 스크립트·고정 의존성·개발 인수인계 문서 포함",
            "빌드 매니페스트·버전별 이력을 ZIP에 포함하고 최종 체크섬은 ZIP 옆 파일로 제공",
        ],
        "changes_en": [
            "Added experimental time-based chord-voicing analysis as a separate result category",
            "Shows chord symbol, pitch classes, bass/inversion, register, spacing, and confidence from the guitar stem",
            "Labels common barre shapes as playable candidates, never as fingerings detected from the recording",
            "Persists dated UTF-8 runtime logs in the portable data/logs folder",
            "Exports source, session/daily logs, bilingual history, and environment diagnostics as a DebugBundle ZIP from Developer options",
            "Includes full source, build scripts, pinned dependencies, and bilingual developer handoff documentation for continuation on another Windows PC",
            "Includes the build manifest and versioned history in the ZIP, with final checksums provided beside it",
        ],
        "known_issues": [
            "음원만으로 정확한 기타 현·프렛 조합을 유일하게 판별할 수 없어 후보 운지는 검출 결과가 아님",
            "퍼즈·피치 이펙트·빠른 리프·카포·드롭 튜닝·AI 분리 누출은 코드 판정을 흐릴 수 있음",
            "보이싱 신뢰도는 템플릿 점수 차이이며 통계적 정확도 확률이 아님",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "Exact strings and frets are not uniquely identifiable from audio; candidate shapes are not detected fingerings",
            "Fuzz, pitch effects, fast riffs, capo/drop tunings, and source-separation bleed can confuse chord estimates",
            "Voicing confidence is a template-score margin, not a statistical accuracy probability",
            "This unsigned development build may trigger a Windows warning",
        ],
    },
    {
        "version": "0.0.02",
        "date": "2026-09-02",
        "status": "비공개 프리뷰 패치",
        "status_en": "Private preview patch",
        "changes": [
            "한국어/English 실시간 언어 전환과 언어별 UI 폰트 적용",
            "한국어는 맑은 고딕, 영어는 Arial Narrow를 기본 UI 글꼴로 사용",
            "추천 설명·오류·진단·개발자 블록·변경 기록·HTML/JSON 결과의 이중 언어화",
            "확장 가능한 멀티이펙터 선택기와 장치별 지원 상태 표시",
            "Tone Master Pro만 활성화하고 Neural DSP Quad Cortex 및 Line 6 Helix Family는 미구현 상태로 등록",
            "추가 장치 두 개를 나중에 이름 붙일 수 있는 예약 슬롯으로 유지",
            "EXE와 문서를 함께 제공하는 Windows 배포 ZIP 추가",
            "45초 제한을 제거하고 끝 시간 0/빈칸으로 전체 곡을 최대 20분까지 분석",
            "Demucs htdemucs_6s로 건반·베이스·드럼·보컬·기타 외 소리를 분리하고 guitar stem만 DSP 분석",
            "30초 단위 AI 분리로 5분 이상 긴 곡의 메모리 사용량 제한 및 조각별 진행 상태 표시",
            "로컬 파일이 없을 때 Windows PC 재생음(WASAPI loopback) 또는 오디오 입력을 임시 WAV로 녹음",
            "AI 분석 취소, 녹음 중지, 분리 모델 캐시 상태와 상세 오류 표시",
            "YouTube 자동 추출 대신 정상 브라우저 재생음을 녹음하는 입력 경로 제공",
        ],
        "changes_en": [
            "Added live Korean/English switching with language-specific UI fonts",
            "Uses Malgun Gothic for Korean and Arial Narrow for English",
            "Localized recipe explanations, errors, diagnostics, developer blocks, changelog, and HTML/JSON output",
            "Added an extensible multi-effects selector with per-device support status",
            "Tone Master Pro remains active; Neural DSP Quad Cortex and Line 6 Helix Family are listed as not implemented",
            "Kept two additional unnamed device slots for future units",
            "Added a Windows distribution ZIP containing the EXE and documentation",
            "Removed the 45-second limit; End 0/blank analyzes up to 20 minutes of the full item",
            "Uses Demucs htdemucs_6s to separate keys, bass, drums, vocals, and other sounds, then analyzes only the guitar stem",
            "Processes long tracks in 30-second AI chunks to bound memory and report per-chunk progress",
            "Records Windows PC playback (WASAPI loopback) or an audio input to a temporary WAV when no local file is available",
            "Added analysis cancellation, recording stop, model-cache diagnostics, and detailed separation errors",
            "Provides browser-playback recording instead of automated YouTube extraction",
        ],
        "known_issues": [
            "Tone Master Pro 외 장치는 선택 화면만 제공하며 분석 버튼이 비활성화됨",
            "장치별 카탈로그 구현에는 해당 제조사의 공식 매뉴얼·모델/파라미터 자료가 필요함",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
            "Demucs 6-stem의 guitar 출력은 실험적이므로 잔여 악기 누출과 인공음이 생길 수 있음",
            "AI 모델을 ZIP에 재배포하지 않아 첫 기타 분리 실행에는 인터넷 연결이 필요함",
            "CPU에서 5분 이상 곡 분리는 재생 시간보다 오래 걸릴 수 있음",
        ],
        "known_issues_en": [
            "Devices other than Tone Master Pro are selection placeholders and disable analysis",
            "Each new device catalog requires official manuals and model/parameter documentation",
            "This unsigned development build may trigger a Windows warning",
            "The Demucs 6-stem guitar output is experimental and may contain bleed or artifacts",
            "The AI weights are not redistributed in the ZIP, so the first guitar-isolation run needs internet access",
            "CPU separation of tracks over five minutes can take longer than real time",
        ],
    },
    {
        "version": "0.0.01",
        # 이전 릴리스 날짜가 다음 빌드의 BUILD_DATE 변경을 따라가지 않게 고정한다.
        "date": "2026-09-02",
        "status": "최초 비공개 프리뷰",
        "status_en": "Initial private preview",
        "changes": [
            "로컬 오디오 3~45초 구간의 스펙트럼·다이내믹·공간 특징 분석",
            "Tone Master Pro 펌웨어 1.8.58 / Model Guide Rev. J 기반 추천 3종",
            "픽업·풀믹스·출력 연결 방식에 따른 레시피 보정",
            "블록 순서, 실제 모델명, 노브 시작값과 추천 이유 표시",
            "JSON 데이터와 단일 HTML 분석 리포트 내보내기",
            "개발자 옵션: 처리 시퀀스 블록 다이어그램, 단계 로그, 클릭형 한글 코드 뷰어",
            "YouTube 주소는 출처 기록·브라우저 열기 전용이며 음원 다운로드는 제공하지 않음",
        ],
        "changes_en": [
            "Analyzes a 3–45 second local-audio segment for spectral, dynamic, and spatial features",
            "Provides three Tone Master Pro recipes for firmware 1.8.58 / Model Guide Rev. J",
            "Corrects recipes for pickup, full-mix influence, and output connection",
            "Shows block order, actual model names, knob starting values, and recommendation reasons",
            "Exports machine-readable JSON and a standalone HTML analysis report",
            "Developer options include a sequence diagram, live log, and clickable Korean-commented source viewer",
            "YouTube URLs are reference/browser shortcuts only; no audio download is provided",
        ],
        "known_issues": [
            "공개된 프리셋 쓰기 API가 없어 TMP/Pro Control에 값을 수동 적용해야 함",
            "기타 분리 모델이 없는 휴리스틱 프리뷰이므로 풀믹스의 분석 오차가 큼",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "No public preset-writing API is available, so values must be entered manually in TMP/Pro Control",
            "This heuristic preview has no guitar-separation model and is less accurate on full mixes",
            "This unsigned development build may trigger a Windows warning",
        ],
    }
]


TEMPLATES: list[dict] = [
    {
        "id": "blackface_clean",
        "name": "블랙패널 스튜디오 클린",
        "name_en": "Black-panel Studio Clean",
        "archetype": "클린",
        "archetype_en": "Clean",
        "description": "넓은 헤드룸, 단단한 저역과 또렷한 어택",
        "description_en": "Wide headroom, firm lows, and a clear attack",
        "target": {"saturation": 0.10, "brightness": 0.62, "body": 0.48, "compression": 0.22, "ambience": 0.20, "modulation": 0.05},
        "amp": "Fender '65 Twin Reverb",
        "cab": "Fender 2x12 '65 Twin C12K",
        "mic": "Condenser C414",
        "mic_position": "Cone edge / 1.0 in / off-axis",
        "drive": None,
        "mod": None,
        "delay": None,
        "reverb": "'65 Spring Reverb",
        "tags": ["pop", "funk", "country", "pedal platform"],
    },
    {
        "id": "jc_wide_clean",
        "name": "와이드 솔리드스테이트 클린",
        "name_en": "Wide Solid-state Clean",
        "archetype": "클린/코러스",
        "archetype_en": "Clean / Chorus",
        "description": "초고해상도 클린과 넓은 스테레오 코러스",
        "description_en": "Detailed clean tone with wide stereo chorus",
        "target": {"saturation": 0.08, "brightness": 0.70, "body": 0.36, "compression": 0.18, "ambience": 0.28, "modulation": 0.62},
        "amp": "JC Clean",
        "cab": "2x12 JC",
        "mic": "Dynamic MD421",
        "mic_position": "Cone / 2.0 in / off-axis",
        "drive": None,
        "mod": "Chorus Stereo",
        "delay": None,
        "reverb": "Small Hall Reverb",
        "tags": ["80s", "city pop", "ambient", "clean"],
    },
    {
        "id": "deluxe_edge",
        "name": "스무스 디럭스 엣지",
        "name_en": "Smooth Deluxe Edge",
        "archetype": "엣지 오브 브레이크업",
        "archetype_en": "Edge of Breakup",
        "description": "픽킹에 따라 클린과 가벼운 드라이브를 오가는 톤",
        "description_en": "Moves between clean and light drive with picking dynamics",
        "target": {"saturation": 0.28, "brightness": 0.55, "body": 0.48, "compression": 0.34, "ambience": 0.24, "modulation": 0.06},
        "amp": "Fender '65 Deluxe Reverb Blonde NBC",
        "cab": "Fender 1x12 '65 Deluxe C12K",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 1.0 in / on-axis",
        "drive": "Lightyear",
        "mod": None,
        "delay": None,
        "reverb": "'65 Spring Reverb",
        "tags": ["indie", "pop", "roots", "edge"],
    },
    {
        "id": "bassman_blues",
        "name": "트위드 블루스 드라이브",
        "name_en": "Tweed Blues Drive",
        "archetype": "블루스 드라이브",
        "archetype_en": "Blues Drive",
        "description": "따뜻한 중저역과 손끝 반응이 살아 있는 블루스 톤",
        "description_en": "Warm low mids and touch-responsive blues drive",
        "target": {"saturation": 0.42, "brightness": 0.42, "body": 0.62, "compression": 0.42, "ambience": 0.16, "modulation": 0.04},
        "amp": "Fender '59 Bassman Custom",
        "cab": "Fender 4x10 '59 Bassman Greenback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 2.0 in / off-axis",
        "drive": "Blues Maker",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["blues", "roots", "classic"],
    },
    {
        "id": "class_a_chime",
        "name": "클래스 A 차임 크런치",
        "name_en": "Class-A Chime Crunch",
        "archetype": "차임/크런치",
        "archetype_en": "Chime / Crunch",
        "description": "상단의 차임과 개방감 있는 자연스러운 브레이크업",
        "description_en": "Chiming highs with open, natural breakup",
        "target": {"saturation": 0.40, "brightness": 0.72, "body": 0.42, "compression": 0.34, "ambience": 0.22, "modulation": 0.10},
        "amp": "UK 30 Brilliant",
        "cab": "2x12 UK30 Alnico Blue",
        "mic": "Dynamic SM57",
        "mic_position": "Cone edge / 1.0 in / off-axis",
        "drive": "Mythic Drive",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["brit pop", "indie", "jangle", "classic rock"],
    },
    {
        "id": "plexi_crunch",
        "name": "빈티지 브리티시 크런치",
        "name_en": "Vintage British Crunch",
        "archetype": "크런치",
        "archetype_en": "Crunch",
        "description": "다이내믹한 어택과 풍부한 배음의 클래식 록 톤",
        "description_en": "Classic-rock tone with dynamic attack and rich harmonics",
        "target": {"saturation": 0.54, "brightness": 0.56, "body": 0.55, "compression": 0.44, "ambience": 0.12, "modulation": 0.04},
        "amp": "British Plexi",
        "cab": "4x12 British Greenback",
        "mic": "Dynamic SM57",
        "mic_position": "Cone edge / 0.5 in / on-axis",
        "drive": None,
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["classic rock", "rhythm", "70s"],
    },
    {
        "id": "british_800",
        "name": "80년대 브리티시 하드록",
        "name_en": "80s British Hard Rock",
        "archetype": "하드록",
        "archetype_en": "Hard Rock",
        "description": "공격적인 미드와 즉각적인 어택의 리듬 톤",
        "description_en": "Rhythm tone with aggressive mids and immediate attack",
        "target": {"saturation": 0.66, "brightness": 0.60, "body": 0.50, "compression": 0.58, "ambience": 0.12, "modulation": 0.05},
        "amp": "British 800",
        "cab": "4x12 British G12H",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Greenbox 8",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["80s", "hard rock", "punk", "rhythm"],
    },
    {
        "id": "jubilee_lead",
        "name": "브리티시 싱잉 리드",
        "name_en": "British Singing Lead",
        "archetype": "리드",
        "archetype_en": "Lead",
        "description": "집중된 미드와 매끄러운 서스테인의 솔로 톤",
        "description_en": "Focused mids and smooth sustain for melodic solos",
        "target": {"saturation": 0.70, "brightness": 0.52, "body": 0.52, "compression": 0.66, "ambience": 0.32, "modulation": 0.08},
        "amp": "British Jubilee Lead",
        "cab": "4x12 British Jubilee V30",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 1.0 in / on-axis",
        "drive": "Mythic Drive II",
        "mod": None,
        "delay": "Analog Delay",
        "reverb": "Large Plate Reverb",
        "tags": ["lead", "solo", "hard rock"],
    },
    {
        "id": "solo_lead",
        "name": "핫로드 서스테인 리드",
        "name_en": "Hot-rodded Sustain Lead",
        "archetype": "리드/하이게인",
        "archetype_en": "Lead / High Gain",
        "description": "타이트한 어택과 유연한 서스테인의 현대 리드",
        "description_en": "Modern lead with tight attack and fluid sustain",
        "target": {"saturation": 0.76, "brightness": 0.55, "body": 0.46, "compression": 0.70, "ambience": 0.34, "modulation": 0.06},
        "amp": "Solo 100 Overdrive",
        "cab": "4x12 Solo G12H",
        "mic": "Dynamic MD421",
        "mic_position": "Cap edge / 1.0 in / off-axis",
        "drive": "Greenbox 10",
        "mod": None,
        "delay": "Digital Delay",
        "reverb": "Large Plate Reverb",
        "tags": ["lead", "modern rock", "fusion"],
    },
    {
        "id": "evh_blue",
        "name": "타이트 모던 크런치",
        "name_en": "Tight Modern Crunch",
        "archetype": "모던 하드록",
        "archetype_en": "Modern Hard Rock",
        "description": "포화감은 높지만 음 분리가 선명한 블루 채널 톤",
        "description_en": "A saturated blue-channel tone with clear note separation",
        "target": {"saturation": 0.73, "brightness": 0.60, "body": 0.48, "compression": 0.65, "ambience": 0.10, "modulation": 0.04},
        "amp": "EVH 5150IIIS 6L6 Blue",
        "cab": "4x12 EVH 5150IIIS",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Integrator Boost",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["modern rock", "metal", "riff"],
    },
    {
        "id": "evh_red",
        "name": "5150 모던 하이게인",
        "name_en": "5150 Modern High Gain",
        "archetype": "하이게인",
        "archetype_en": "High Gain",
        "description": "강한 포화와 타이트한 저역의 현대 메탈 톤",
        "description_en": "Modern metal tone with heavy saturation and tight lows",
        "target": {"saturation": 0.88, "brightness": 0.58, "body": 0.50, "compression": 0.82, "ambience": 0.08, "modulation": 0.02},
        "amp": "EVH 5150IIIS 6L6 Red",
        "cab": "4x12 EVH 5150IIIS",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Grunt Boost",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["metal", "djent", "high gain", "riff"],
    },
    {
        "id": "double_wreck",
        "name": "아메리칸 대형 하이게인",
        "name_en": "Large American High Gain",
        "archetype": "하이게인",
        "archetype_en": "High Gain",
        "description": "큰 저역과 공격적인 질감의 현대 헤비 톤",
        "description_en": "Modern heavy tone with massive lows and aggressive texture",
        "target": {"saturation": 0.86, "brightness": 0.46, "body": 0.68, "compression": 0.80, "ambience": 0.08, "modulation": 0.02},
        "amp": "Double Wreck",
        "cab": "4x12 Mega V30",
        "mic": "Dynamic MD421",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Greenbox 10",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["metal", "drop tuning", "heavy"],
    },
    {
        "id": "petrol_tight",
        "name": "포커스드 메탈 리듬",
        "name_en": "Focused Metal Rhythm",
        "archetype": "타이트 하이게인",
        "archetype_en": "Tight High Gain",
        "description": "팜뮤트 정의감과 집중된 미드가 우선인 리듬 톤",
        "description_en": "Rhythm tone prioritizing palm-mute definition and focused mids",
        "target": {"saturation": 0.82, "brightness": 0.64, "body": 0.42, "compression": 0.76, "ambience": 0.06, "modulation": 0.02},
        "amp": "Petrol",
        "cab": "4x12 Petrol V30",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.0 in / off-axis",
        "drive": "Integrator Boost",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["metal", "tight", "rhythm"],
    },
    {
        "id": "vintage_fuzz",
        "name": "빈티지 게르마늄 퍼즈",
        "name_en": "Vintage Germanium Fuzz",
        "archetype": "퍼즈",
        "archetype_en": "Fuzz",
        "description": "볼륨 반응이 좋고 따뜻하게 뭉치는 올드스쿨 퍼즈",
        "description_en": "Warm old-school fuzz with responsive volume cleanup",
        "target": {"saturation": 0.80, "brightness": 0.40, "body": 0.58, "compression": 0.72, "ambience": 0.10, "modulation": 0.03},
        "amp": "British 45",
        "cab": "4x12 British Greenback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 2.0 in / off-axis",
        "drive": "Round Fuzz (Germanium)",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["60s", "psychedelic", "vintage fuzz"],
    },
    {
        "id": "wall_fuzz",
        "name": "빅 월 퍼즈",
        "name_en": "Big Wall Fuzz",
        "archetype": "퍼즈",
        "archetype_en": "Fuzz",
        "description": "두꺼운 서스테인과 넓게 퍼지는 벽 같은 퍼즈",
        "description_en": "Thick sustain and a wide wall-of-sound fuzz texture",
        "target": {"saturation": 0.94, "brightness": 0.45, "body": 0.72, "compression": 0.90, "ambience": 0.22, "modulation": 0.04},
        "amp": "Fender '65 Twin Reverb",
        "cab": "Fender 2x12 '65 Twin Creamback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 1.0 in / off-axis",
        "drive": "Big Apple Fuzz",
        "mod": None,
        "delay": None,
        "reverb": "Large Plate Reverb",
        "tags": ["alternative", "shoegaze", "wall of sound", "fuzz"],
    },
    {
        "id": "ambient_clean",
        "name": "스테레오 앰비언트 클린",
        "name_en": "Stereo Ambient Clean",
        "archetype": "앰비언트",
        "archetype_en": "Ambient",
        "description": "넓은 모듈레이션, 긴 딜레이와 홀 리버브의 공간계 톤",
        "description_en": "Wide modulation, long delay, and spacious hall reverb",
        "target": {"saturation": 0.12, "brightness": 0.64, "body": 0.38, "compression": 0.36, "ambience": 0.88, "modulation": 0.58},
        "amp": "JC Clean",
        "cab": "2x12 JC",
        "mic": "Condenser C414",
        "mic_position": "Cone / 3.0 in / off-axis",
        "drive": None,
        "mod": "Chorus Stereo",
        "delay": "Stereo Memory Delay",
        "reverb": "Modulated Large Hall Reverb",
        "tags": ["ambient", "post rock", "worship", "soundscape"],
    },
    {
        "id": "shoegaze_fuzz",
        "name": "앰비언트 퍼즈 레이어",
        "name_en": "Ambient Fuzz Layer",
        "archetype": "퍼즈/앰비언트",
        "archetype_en": "Fuzz / Ambient",
        "description": "두꺼운 퍼즈 뒤에 넓고 긴 공간계를 쌓는 레이어 톤",
        "description_en": "Thick fuzz layered beneath wide, long ambience",
        "target": {"saturation": 0.86, "brightness": 0.52, "body": 0.64, "compression": 0.86, "ambience": 0.78, "modulation": 0.38},
        "amp": "Fender '65 Twin Reverb",
        "cab": "Fender 2x12 '65 Twin Creamback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 2.0 in / off-axis",
        "drive": "Big Apple Fuzz",
        "mod": "Chorus Stereo",
        "delay": "Stereo Memory Delay",
        "reverb": "Large Hall Reverb",
        "tags": ["shoegaze", "post rock", "ambient", "fuzz"],
    },
    {
        "id": "rockbox_direct",
        "name": "80년대 다이렉트 레코딩",
        "name_en": "80s Direct Recording",
        "archetype": "폴리시드/다이렉트",
        "archetype_en": "Polished / Direct",
        "description": "압축된 앰프 톤과 코러스·에코를 한 블록으로 구성",
        "description_en": "Compressed amp tone, chorus, and echo in a single block",
        "target": {"saturation": 0.52, "brightness": 0.58, "body": 0.42, "compression": 0.78, "ambience": 0.56, "modulation": 0.62},
        "amp": None,
        "cab": None,
        "mic": None,
        "mic_position": None,
        "drive": "Rockbox 100",
        "mod": None,
        "delay": None,
        "reverb": "Small Plate Reverb",
        "tags": ["80s", "direct", "studio", "chorus"],
    },
]


KNOWN_MODELS = {
    "amps": sorted({t["amp"] for t in TEMPLATES if t["amp"]}),
    "cabinets": sorted({t["cab"] for t in TEMPLATES if t["cab"]}),
    "effects": sorted(
        {
            item
            for t in TEMPLATES
            for item in (t["drive"], t["mod"], t["delay"], t["reverb"])
            if item
        }
        | {
            "Pedal Comp",
            "Simple Compressor",
            "Metal Gate",
            "Noise Gate",
            "EQ-5 Parametric",
            "Low/High Cut Filter",
        }
    ),
    "microphones": [
        "Dynamic MD421",
        "Dynamic RE20",
        "Dynamic SM57",
        "Dynamic SM7B",
        "Ribbon R121",
        "Condenser C414",
        "Condenser M23",
    ],
}
