"""Tone Master Pro 1.8 계열용 추천 모델 카탈로그.

표시 모델명과 컨트롤명은 Fender Tone Master Pro Model Guide Rev. J를
기준으로 정리했다. 목표 벡터는 공식 측정값이 아니라 이 앱이 사용하는
휴리스틱 값이며, 공개되지 않은 내부 모델 ID는 사용하지 않는다.
"""

from __future__ import annotations


APP_VERSION = "0.0.13"
TARGET_FIRMWARE = "1.8.58"
MODEL_GUIDE_REVISION = "Rev. J (2026-07)"
BUILD_DATE = "2026-10-04"


# 앱 내부의 변경 기록 화면과 배포 문서가 함께 사용하는 단일 원본이다.
# 이후 패치는 0.0.02, 0.0.03, 0.0.04처럼 한 단계씩 올리고 최신 항목을 맨 위에 둔다.
CHANGELOG: list[dict] = [
    {
        "version": "0.0.13",
        "date": BUILD_DATE,
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "코드·보이싱 결과를 한 줄 4마디, 페이지당 16마디 코드표로 표시",
            "BPM·박자·첫 마디 시작 위치를 보정하고 미확정·한 마디 안의 코드 변화를 보존",
            "표준 튜닝 기타의 구성음 검증 운지 후보를 확장하고 실제 연주 검출과 구분",
            "긴 곡에서 기존 96개 표시 상한으로 생략되던 코드 이벤트를 페이지 단위로 유지",
            "채보 알고리즘 조사와 정답 주석 기반 후속 평가 계획 문서화",
        ],
        "changes_en": [
            "Displays chord/voicing results as four bars per row and sixteen bars per page",
            "Editable BPM, meter and first downbeat preserve unknown spans and within-bar changes",
            "Expands pitch-validated standard-tuning guitar suggestions, distinct from detected performance",
            "Retains long-song chord events beyond the previous 96-event display limit",
            "Documents transcription research and a ground-truth evaluation plan",
        ],
        "known_issues": [
            "마디는 일정 템포의 보정 가능한 참고 격자이며 자동 다운비트 채보가 아님",
            "운지는 이론 후보이며 실제 손가락·현·프렛 검출이 아님; 7구성음의 완전한 13화음은 6현에 표시하지 않음",
            "신경망 채보 모델은 도입하지 않았으며 실제 곡 정확도 향상을 측정하지 않음",
        ],
        "known_issues_en": [
            "Bars use an editable constant-tempo guide, not detected downbeats",
            "Shapes are theoretical suggestions, not detected fingers; seven-tone 13ths cannot fit six strings",
            "No neural transcription model is integrated and real-song accuracy gains are not measured",
        ],
    },
    {
        "version": "0.0.12",
        "date": "2026-10-02",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "7sus2·11·13·마이너 메이저·6/9·변형 텐션을 포함해 코드 유형 확대",
            "12개 근음의 코드·음계·다이어토닉 화음을 구성음과 건반으로 보는 독립 참고표 추가",
            "펜타토닉·모드 등 음계와 개별 코드 판별을 구분하고 다이어토닉 3화음·7화음을 나란히 표시",
            "6/9 코드 이름을 슬래시 베이스와 혼동하지 않도록 믹스 결과 표시 보완",
            "단발 확장음 후보 때문에 반복되는 화음 근거가 사라지지 않도록 시간 연결 후보 선택 보완",
        ],
        "changes_en": [
            "Expands chord qualities with 7sus2, 11ths, 13ths, minor-major, 6/9 and altered tensions",
            "Adds a separate 12-root chord, scale and diatonic reference with notes and keyboard display",
            "Separates pentatonic/mode references from chord detection and shows diatonic triads/sevenths",
            "Preserves 6/9 chord names when removing non-guitar slash-bass claims from mixed harmony",
            "Preserves repeated local chord evidence when isolated extension candidates compete during temporal tracking",
        ],
        "known_issues": [
            "참고표는 이론 조회이며 실제 음원의 키·음계 자동 판정이나 운지 검출이 아님",
            "확장화음의 구성음이 빠지거나 믹스·분리 누출이 복잡하면 후보가 틀리거나 미확정으로 남을 수 있음",
            "합성 검증은 실제 곡 정답률을 뜻하지 않으며 수동 화면·청감·CUDA·코드 서명은 별도 검증",
        ],
        "known_issues_en": [
            "The reference is theoretical lookup, not detected key, scale or played fingering",
            "Missing extension tones, dense mixes and separation bleed can yield wrong or unknown candidates",
            "Synthetic checks do not measure real-song accuracy; manual GUI/listening, CUDA and signing require separate validation",
        ],
    },
    {
        "version": "0.0.11",
        "date": "2026-09-30",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "코드·보이싱의 화음 후보와 관측 근거를 보완하고 모호한 후보를 구분해 표시",
            "코드 근거 점수를 정답률과 구분하며 실제 기타 줄·프렛을 확정하지 않는 안내 유지",
            "분석 입력으로 연결되지 않던 YouTube 참고 URL 칸과 브라우저 열기 버튼 제거",
            "권한 있는 로컬 파일·녹음 입력, 선택 악기 제거와 C ABI 2 실시간 DSP 유지",
        ],
        "changes_en": [
            "Improves chord/voicing candidates and observed evidence, displaying ambiguous alternatives separately",
            "Distinguishes chord evidence scores from accuracy and retains the boundary against claiming detected strings/frets",
            "Removes the reference-only YouTube URL field and browser shortcut that were not analysis inputs",
            "Retains authorized local-file/recording input, selective stem removal and C ABI 2 live DSP",
        ],
        "known_issues": [
            "복잡한 믹스·왜곡·분리 누출에서 코드 후보가 틀릴 수 있으며 실제 곡의 정답률이나 확정 타브를 보증하지 않음",
            "YouTube 링크의 자동 추출·분석은 지원하지 않으며 저작권 허가와 플랫폼 이용 조건은 별개",
            "AI 분리 품질·실제 장치 캡처·CUDA·청감과 코드 서명 검증은 자동 회귀 테스트와 구분",
        ],
        "known_issues_en": [
            "Dense mixes, distortion and separation bleed can produce wrong candidates; no real-song accuracy or detected-tablature guarantee",
            "Automatic YouTube extraction/analysis is not supported; copyright permission and platform conditions are separate",
            "Separation quality, physical capture, CUDA, listening and code-signing validation are separate from automated regression tests",
        ],
    },
    {
        "version": "0.0.10",
        "date": "2026-09-20",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "악기 제거에서 새 입력을 선택하면 이전 결과·진행률을 초기화해 잘못된 완료 표시 방지",
            "출력 경로의 끊어진 심볼릭 링크도 기존 항목으로 처리해 기본 이름 선택과 비덮어쓰기 검증 보완",
            "기타 분리의 잘린 WAV 입력을 거부하고 실패 시 중간 파일 정리",
            "GUI 없이 실제 모델로 기타·피아노 제거와 취소·진행률·원본 보존을 점검하는 별도 CLI 진단 추가",
            "진단용 출력 WAV는 정리하고 JSON에서 음원·출력 파일명과 모델 경로 제외",
            "v0.0.09의 선택 악기 제거와 C ABI 2 float32·실시간 DSP 진단 유지",
        ],
        "changes_en": [
            "Resets old stem-removal results and progress when selecting a new source",
            "Treats dangling output symlinks as existing entries in default-name selection and no-overwrite validation",
            "Rejects truncated WAV input during guitar isolation and cleans intermediate files on failure",
            "Adds a separate headless CLI check using the real model for guitar/piano removal, cancellation, progress and source preservation",
            "Cleans diagnostic WAV output and omits media/output filenames and model paths from the JSON report",
            "Retains v0.0.09 selective stem removal and C ABI 2 float32/live-DSP diagnostics",
        ],
        "known_issues": [
            "AI 분리의 악기 누출·빠진 소리·잔향·왜곡 가능성은 유지되며 분리 품질 개선 모델은 아님",
            "별도 CLI 진단 통과는 전체 곡 수동 UI·청감 품질·첫 다운로드·오프라인·CUDA 검증을 뜻하지 않음",
            "추론 중 취소는 현재 블록 또는 네트워크 대기 뒤 반영될 수 있으며 ETA는 제공하지 않음",
            "C++ 장치 입출력·ASIO·독점 모드·하드 실시간·자동 기기 쓰기는 포함하지 않음",
        ],
        "known_issues_en": [
            "AI bleed, missing sound, ambience changes and artifacts remain; this is not a new separation-quality model",
            "A headless CLI pass does not validate manual full-song UI operation, listening quality, first download, offline mode or CUDA",
            "Cancellation can wait for an inference block or network operation; no ETA is provided",
            "No C++ device I/O, ASIO, exclusive mode, hard-real-time guarantees or automatic device writing",
        ],
    },
    {
        "version": "0.0.09",
        "date": "2026-09-19",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "로컬 오디오·영상의 Demucs 6개 스템에서 선택한 악기를 제외해 새 스테레오 WAV로 저장",
            "C ABI 2의 float32 직접 입력으로 정렬된 연속 캡처 PCM의 불필요한 float64 배열 변환 제거",
            "기존 double 입력의 정밀도와 C++의 NaN/Inf·클리핑·부분 창·평활화 계약 유지",
            "입력 프레임·완성 FFT 창·미완성 버퍼 수를 엔진에서 조회하고 초기화·종료 수명 검증",
            "실시간 DSP 처리 시간과 창·버퍼 상태를 최신 프레임과 함께 표시하며 이전 세션 갱신 차단",
            "ABI 1 DLL 혼용을 검출하고 자동 NumPy 폴백과 실제 ABI 2 배포 검증을 구분",
        ],
        "changes_en": [
            "Adds local six-stem Demucs removal that excludes selected instruments and writes a new stereo WAV",
            "Adds direct float32 input through C ABI 2, avoiding the input-sized float64 conversion for aligned contiguous capture PCM",
            "Preserves double-input precision and native sanitization, clipping, partial-window and smoothing contracts",
            "Exposes accepted input frames, completed FFT windows and pending frames with reset and lifetime checks",
            "Shows live DSP push duration and window/buffer state alongside the latest frame while rejecting stale sessions",
            "Detects mixed ABI 1 DLLs and distinguishes automatic NumPy fallback from required ABI 2 release verification",
        ],
        "known_issues": [
            "스템 제거는 AI 추정이므로 악기 누출·잔향·왜곡이 남을 수 있고 원본 트랙을 정확히 복원하지 않음",
            "DSP 처리 시간은 장치 캡처·화면 표시·AI 분석·오디오 왕복 지연을 포함하지 않음",
            "입력 정렬이나 연속성에 따라 복사가 필요하며 출력 복사·잠금·SoundCard 캡처는 유지됨",
            "C++ 장치 입출력·ASIO·독점 모드·하드 실시간·새 톤 지표·기기 자동 쓰기는 포함하지 않음",
        ],
        "known_issues_en": [
            "Stem removal is an AI estimate; bleed, ambience and artifacts can remain and it does not reconstruct original multitracks",
            "DSP duration excludes device capture, rendering, AI analysis and round-trip audio latency",
            "Unaligned or noncontiguous input may require a copy; output copies, locks and SoundCard capture remain",
            "No C++ device I/O, ASIO, exclusive mode, hard-real-time guarantees, new tone meters or automatic device writing",
        ],
    },
    {
        "version": "0.0.08",
        "date": "2026-09-10",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "실시간 PCM 누적·채널별 FFT·최근 4프레임 평활화를 사전 할당 버퍼의 C++17 DSP 엔진으로 분리",
            "버전 C ABI 1과 ctypes 브리지로 번들 DLL 호환성·수명·잠금을 관리하고 실제 C++/NumPy 백엔드 표시",
            "DLL 누락·비호환 시 NumPy 기준 경로로 폴백하며 미완성 FFT 입력은 다음 블록까지 보존",
            "네이티브 소스·헤더·브리지·테스트·명시적 Zig 빌드 경로를 포터블 개발 패키지에 포함",
            "SoundCard 캡처·Python/Tk·AI 분리·오프라인 톤/Reference/코드 분석과 기존 UI 보완 유지",
        ],
        "changes_en": [
            "Moves live PCM accumulation, per-channel FFT and four-frame smoothing into a C++17 DSP engine with preallocated buffers",
            "Uses versioned C ABI 1 and a ctypes bridge for bundled-DLL compatibility, lifetime and locking, showing the actual C++/NumPy backend",
            "Falls back to the NumPy reference path when native code is missing or incompatible and retains partial FFT input for the next block",
            "Includes native source/header, bridge, tests and an explicit Zig build path in the portable developer package",
            "Preserves SoundCard capture, Python/Tk, AI isolation, offline tone/Reference/chord analysis and previous UI fixes",
        ],
        "known_issues": [
            "전환 범위는 실시간 DSP이며 C++ 장치 입출력·ASIO·WASAPI Exclusive·하드 실시간 엔진이 아님",
            "Python 복사·잠금과 공유 모드 캡처 비용이 남음; 전체 곡 Demucs 가속이나 모든 입력에서의 성능 향상을 보증하지 않음",
            "실시간 톤 특징·Match %·자동 EQ/TMP 설정·기기 프리셋 쓰기는 포함하지 않음",
            "코드·보이싱은 실험적 참고이며 정답률·확정 타브가 아님; CUDA 실제 하드웨어 검증과 코드 서명은 별도",
        ],
        "known_issues_en": [
            "The migration covers live DSP, not C++ device I/O, ASIO, WASAPI Exclusive or a hard-real-time engine",
            "Python copies, locks and shared-mode capture remain; no whole-song Demucs acceleration or universal performance improvement is guaranteed",
            "Live tone-feature/Match-percent meters, automatic EQ/TMP settings and device preset writing are not included",
            "Chord/voicing output remains experimental guidance, not accuracy or detected tablature; real CUDA validation and code signing are separate",
        ],
    },
    {
        "version": "0.0.07",
        "date": "2026-09-08",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "스테레오 역상 상쇄와 배음·잡음 영향을 줄이고 반복되는 코드 근거를 확인하는 보수적 타임라인 개선",
            "기타 분리음이 약하면 원본 믹스 화성을 별도 참고 분석하며 출처·미확정 구간·진단 수치 표시",
            "원본 화성 참고를 기타 운지·역위로 표현하지 않고 톤 추천과 Reference 분석 신호는 유지",
            "GUI·JSON·HTML의 선택 구간 시간과 코드 근거·한계 안내 통일",
            "Windows 작업 영역에 맞춘 창 크기와 스크롤 가능한 고정 상태 영역으로 분석 후 하단 잘림 개선",
        ],
        "changes_en": [
            "Improves conservative chord timelines with phase-safe pitch evidence, harmonic/noise rejection and repeated-window support",
            "Checks original-mix harmony separately when guitar-stem evidence is weak, labeling source, unknown spans and diagnostics",
            "Never presents mix harmony as detected guitar shapes or inversions; tone and Reference analysis signals remain unchanged",
            "Aligns selected-file timestamps, evidence and limitations across GUI, JSON and HTML",
            "Fits startup to the Windows work area and bounds the scrollable status footer to prevent post-analysis clipping",
        ],
        "known_issues": [
            "코드는 실험적 후보이며 정답 확률·악보·기타 타브가 아님; 빠른 코드 변화와 약한 근거는 미확정일 수 있음",
            "원본 믹스 참고에는 건반·베이스 등도 포함됨; 매우 약한 기타 stem의 톤 추천 정확도를 보증하지 않음",
            "서명 없는 CPU 프리뷰이며 실제 CUDA·ASIO·C++ 실시간 엔진·자동 프리셋 쓰기는 제공하지 않음",
        ],
        "known_issues_en": [
            "Chords are experimental candidates, not accuracy probabilities, notation or guitar tabs; fast or weak evidence may stay unknown",
            "Original-mix harmony includes other instruments and does not validate tone recipes from a very weak guitar stem",
            "Unsigned CPU preview; no verified CUDA hardware run, ASIO, C++ real-time engine or automatic preset writing",
        ],
    },
    {
        "version": "0.0.06",
        "date": "2026-09-07",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "로컬 파일 또는 Demucs로 분리한 guitar stem에서 레벨 정규화 기준 스펙트럼을 생성해 분석 결과에 저장",
            "기존 WASAPI 실시간 모니터를 Current 입력으로 재사용하는 Reference Compare 탭 추가",
            "Low·Low Mid·Mid·Presence·Treble·Air 6밴드의 Reference·Current·Δ(Current−Reference) 비교 표시",
            "샘플레이트가 다른 기준과 실시간 입력을 같은 주파수 그리드로 보간하고 전체 레벨 영향을 제거한 톤 형상 비교",
            "주파수별 차이를 0 dB 중심 그래프로 표시하고 무음·비유한 입력·나이퀴스트 범위를 안전하게 처리",
            "기준 프로필 생성·밴드 집계·실시간 비교와 Tk 표시를 실제 오디오 장치 없이 검증하는 회귀 테스트 추가",
            "분석 화면에 단계 가중 전체 진행률과 250 ms 타이머 기반 경과 시간을 상시 표시",
            "모델의 실제 수신량·파일 진행률과 Demucs 내부 완료 블록 기준 음원 처리 초를 표시하고 블록 경계 취소 지원",
            "콘솔 없는 EXE의 stdout·stderr None 출력 오류를 방지하고 공식 safetensors 캐시 우선 로딩으로 조용한 구형 모델 폴백 제거",
            "모델 준비 실패를 네트워크·캐시 권한/디스크·메모리·기타 모델/런타임 원인으로 구분",
        ],
        "changes_en": [
            "Builds and stores a level-normalized reference spectrum from the analyzed local file or Demucs-isolated guitar stem",
            "Added a Reference Compare tab that reuses the existing WASAPI live monitor as the Current input",
            "Shows Reference, Current, and delta (Current minus Reference) for Low, Low Mid, Mid, Presence, Treble, and Air",
            "Interpolates reference and live input onto a common frequency grid and removes overall-level bias for tone-shape comparison",
            "Plots frequency-by-frequency difference around a 0 dB center while safely handling silence, non-finite input, and Nyquist limits",
            "Added hardware-free regression coverage for profile generation, band aggregation, live comparison, and Tk rendering",
            "Always displays stage-weighted overall analysis progress and elapsed time on a 250 ms UI timer",
            "Reports actual model transfer bytes/file progress and audio duration from completed internal Demucs blocks, with block-boundary cancellation",
            "Guards missing stdout/stderr in the windowed EXE and explicitly loads cached official safetensors without silent legacy-model fallback",
            "Distinguishes network, cache permissions/disk, memory, and other model/runtime setup failures",
        ],
        "known_issues": [
            "Reference Compare는 레벨 정규화된 스펙트럼 차이이며 통계적 정확도나 매칭 확률이 아님",
            "분석 전체 %는 단계 진행률이며 남은 시간의 비율이나 ETA가 아님; 진행 중인 추론 블록·네트워크 대기에서는 갱신과 취소가 지연될 수 있음",
            "Brightness·Body·Gain·Compression·Ambience 실시간 미터와 Match %는 후속 버전 범위임",
            "차이를 자동 EQ/TMP 설정으로 변환하거나 프리셋을 기기에 쓰지 않음",
            "기준 URL은 외부 브라우저 열기와 출처 기록 전용이며 URL의 오디오를 다운로드·분석하지 않음",
            "Python/NumPy와 WASAPI 공유 모드 기반이며 C++·ASIO·WASAPI Exclusive 엔진은 후속 범위임",
            "실제 지연과 사용 가능 장치는 Windows 드라이버·오디오 인터페이스·loopback 지원에 따라 달라짐",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "Reference Compare is a level-normalized spectral difference, not statistical accuracy or a match probability",
            "Overall analysis percentage is stage progress, not a time estimate or ETA; an active inference block or network wait can delay updates and cancellation",
            "Live Brightness, Body, Gain, Compression, Ambience, and Match-percent meters remain later-version work",
            "It does not convert differences into automatic EQ/TMP settings or write presets to the device",
            "Reference URLs are browser shortcuts and source records only; their audio is not downloaded or analyzed",
            "The path uses Python/NumPy and WASAPI shared mode; C++, ASIO, and WASAPI Exclusive remain future work",
            "Actual latency and available devices depend on Windows drivers, the audio interface, and loopback support",
            "This unsigned development build may trigger a Windows warning",
        ],
    },
    {
        "version": "0.0.05",
        # 이전 릴리스 날짜가 다음 빌드의 BUILD_DATE 변경을 따라가지 않게 고정한다.
        "date": "2026-09-05",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "선택한 Windows 오디오 입력 또는 PC 재생음 loopback을 여는 실시간 스펙트럼 탭 추가",
            "입력 파형, 20 Hz~20 kHz 로그 스펙트럼, RMS·Peak dBFS와 스펙트럼 중심 주파수 표시",
            "좌우 역상도 사라지지 않도록 채널별 NumPy FFT 파워를 평균하고 무음·NaN·무한대 입력을 안전하게 처리",
            "2,048 샘플 블록과 최근 4프레임 선형 파워 평활화로 약 20 Hz의 안정적인 시각 갱신 제공",
            "최신 프레임 하나만 유지하는 bounded 큐와 세션별 취소 신호로 장시간 모니터링의 지연·메모리 증가 방지",
            "녹음·AI 분석·하드웨어 검사·언어 전환과 실시간 장치 사용을 상호 배타적으로 관리",
            "스펙트럼·녹음 계층·Tk Canvas 표시를 실제 장치 없이 검증하는 결정론적 회귀 테스트 추가",
        ],
        "changes_en": [
            "Added a Live Spectrum tab that opens the selected Windows audio input or PC-playback loopback device",
            "Shows the input waveform, 20 Hz-20 kHz log spectrum, RMS/peak dBFS, and spectral centroid",
            "Averages per-channel NumPy FFT power so antiphase stereo remains visible and safely sanitizes silence, NaN, and infinite samples",
            "Uses 2,048-sample blocks and a four-frame linear-power smoother for a stable visual refresh near 20 Hz",
            "Keeps only the newest frame in a bounded queue and uses per-session cancellation to prevent long-session lag and memory growth",
            "Mutually excludes live-device use from recording, AI analysis, hardware probing, and language rebuilds",
            "Added deterministic hardware-free regression coverage for spectrum DSP, capture streaming, and Tk Canvas rendering",
        ],
        "known_issues": [
            "실시간 스펙트럼은 선택한 원시 입력을 보여주는 시각 분석기이며 Demucs 분리·레시피 추천과 아직 연결되지 않음",
            "WASAPI 공유 모드 기반 약 20 Hz 화면 갱신으로, ASIO·WASAPI Exclusive·하드 실시간 처리는 후속 C++ 엔진 범위임",
            "실제 지연과 사용 가능 장치는 Windows 드라이버·오디오 인터페이스·loopback 지원에 따라 달라짐",
            "현재 포터블 EXE는 CPU 런타임을 포함하며 CUDA는 호환 NVIDIA PC의 별도 소스 환경에서 설치·재빌드해야 함",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "Live Spectrum visualizes the selected raw input and is not yet connected to Demucs isolation or recipe recommendations",
            "It uses WASAPI shared mode with a visual refresh near 20 Hz; ASIO, WASAPI Exclusive, and hard real-time processing remain future C++ engine work",
            "Actual latency and available devices depend on Windows drivers, the audio interface, and loopback support",
            "The portable EXE contains the CPU runtime; CUDA requires a separate source environment and rebuild on a compatible NVIDIA PC",
            "This unsigned development build may trigger a Windows warning",
        ],
    },
    {
        "version": "0.0.04",
        "date": "2026-09-04",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "AI 기타 분리의 자동/CPU/CUDA 연산 선택과 CUDA 가용성·GPU 모델·VRAM 진단 추가",
            "Demucs 전체/조각별 추론 시간, 실시간 배수와 최대 GPU 메모리 사용량을 성능 진단에 표시",
            "CUDA를 사용할 수 없을 때 자동 모드가 CPU로 안전하게 폴백하고 선택값을 다음 실행에도 유지",
            "코드·보이싱 분석의 반복 계산을 캐시하고 NumPy 벡터 연산으로 옮겨 네이티브 DSP 경로 최적화",
            "FRFR, 실제 캐비닛용 파워앰프, 기타 앰프 전면 입력별 Amp/Cab 포함 규칙과 적용 순서를 분리",
            "FRFR Cabinet 컷과 중복되던 별도 EQ를 제거하고 실제 캐비닛 경로의 기준 Cabinet 정보를 보존",
            "고해상도 배율·작은 화면에서도 분석 버튼까지 접근할 수 있도록 입력 카드를 세로 스크롤 방식으로 개선",
            "C++은 전체 재작성 대신 후속 실시간 오디오·링 버퍼·FFT·ASIO 엔진 경계로 계획",
            "CPU 포터블 배포와 별도로 NVIDIA CUDA 소스 환경을 설치·재빌드하는 개발 경로 문서화",
        ],
        "changes_en": [
            "Added Auto/CPU/CUDA compute selection for guitar isolation with CUDA availability, GPU model, and VRAM diagnostics",
            "Reports total/per-chunk Demucs inference time, real-time factor, and peak GPU-memory use in performance diagnostics",
            "Auto mode safely falls back to CPU when CUDA is unavailable and persists the selected preference",
            "Optimized chord/voicing analysis by caching repeated data and moving inner work to native NumPy vector operations",
            "Separated Amp/Cab inclusion rules and application steps for FRFR, power amp with a real cabinet, and guitar-amp front input",
            "Removed the standalone EQ that duplicated FRFR cabinet cuts while preserving reference-cab information for real-cabinet routes",
            "Made the input card vertically scrollable so Analyze remains reachable on high-DPI and smaller displays",
            "Keeps the Python application and reserves C++ for a later real-time audio, ring-buffer, FFT, and ASIO engine boundary",
            "Documented a separate NVIDIA CUDA source-environment install and rebuild path alongside the CPU portable distribution",
        ],
        "known_issues": [
            "현재 포터블 EXE는 CPU 런타임을 포함하며 CUDA는 호환 NVIDIA PC의 별도 소스 환경에서 설치·재빌드해야 함",
            "이번 개발 PC에는 CUDA 지원 GPU가 없어 실제 GPU Demucs 추론과 VRAM 측정은 하드웨어 검증하지 못함",
            "GPU 가속 여부와 속도는 NVIDIA 드라이버·PyTorch CUDA 빌드·VRAM 및 곡 길이에 따라 달라짐",
            "C++ 실시간/ASIO 엔진은 로드맵이며 이 버전에 실시간 오디오 처리나 기기 프리셋 전송은 포함되지 않음",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "The portable EXE contains the CPU runtime; CUDA requires a separate source environment and rebuild on a compatible NVIDIA PC",
            "This development PC has no CUDA-capable GPU, so real GPU Demucs inference and VRAM reporting were not hardware-validated",
            "GPU acceleration and speed depend on the NVIDIA driver, PyTorch CUDA build, available VRAM, and track length",
            "The C++ real-time/ASIO engine remains roadmap work; this version adds neither real-time audio processing nor preset transfer",
            "This unsigned development build may trigger a Windows warning",
        ],
    },
    {
        "version": "0.0.03",
        # 이전 릴리스 날짜가 다음 빌드의 BUILD_DATE 변경을 따라가지 않게 고정한다.
        "date": "2026-09-03",
        "status": "공개 개발 프리뷰",
        "status_en": "Public development preview",
        "changes": [
            "별도 결과 카테고리에 시간대별 코드 보이싱(실험) 분석 추가",
            "guitar stem의 코드명·구성음·베이스/역위·음역·간격·신뢰도 표시",
            "오디오에서 검출한 운지로 오인하지 않도록 일반적인 바레 운지를 '연주 후보'로 분리 표시",
            "앱 실행 로그를 포터블 data/logs 폴더에 날짜별 UTF-8 파일로 영구 기록",
            "개발자 탭에서 소스·세션/일별 로그·한영 이력·환경 진단을 DebugBundle ZIP으로 내보내기",
            "다른 Windows PC에서 실행과 개발을 이어갈 전체 소스·빌드 스크립트·고정 의존성·개발 인수인계 문서 포함",
            "빌드 매니페스트·버전별 이력을 ZIP에 포함하고 최종 체크섬은 ZIP 옆 파일로 제공",
        ],
        "changes_en": [
            "Added experimental time-based chord-voicing analysis as a separate result category",
            "Shows chord symbol, pitch classes, bass/inversion, register, spacing, and confidence from the guitar stem",
            "Labels common barre shapes as playable candidates, never as fingerings detected from the recording",
            "Persists dated UTF-8 runtime logs in the portable data/logs folder",
            "Exports source, session/daily logs, bilingual history, and environment diagnostics as a DebugBundle ZIP from Developer options",
            "Includes full source, build scripts, pinned dependencies, and bilingual developer handoff documentation for continuation on another Windows PC",
            "Includes the build manifest and versioned history in the ZIP, with final checksums provided beside it",
        ],
        "known_issues": [
            "음원만으로 정확한 기타 현·프렛 조합을 유일하게 판별할 수 없어 후보 운지는 검출 결과가 아님",
            "퍼즈·피치 이펙트·빠른 리프·카포·드롭 튜닝·AI 분리 누출은 코드 판정을 흐릴 수 있음",
            "보이싱 신뢰도는 템플릿 점수 차이이며 통계적 정확도 확률이 아님",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "Exact strings and frets are not uniquely identifiable from audio; candidate shapes are not detected fingerings",
            "Fuzz, pitch effects, fast riffs, capo/drop tunings, and source-separation bleed can confuse chord estimates",
            "Voicing confidence is a template-score margin, not a statistical accuracy probability",
            "This unsigned development build may trigger a Windows warning",
        ],
    },
    {
        "version": "0.0.02",
        "date": "2026-09-02",
        "status": "비공개 프리뷰 패치",
        "status_en": "Private preview patch",
        "changes": [
            "한국어/English 실시간 언어 전환과 언어별 UI 폰트 적용",
            "한국어는 맑은 고딕, 영어는 Arial Narrow를 기본 UI 글꼴로 사용",
            "추천 설명·오류·진단·개발자 블록·변경 기록·HTML/JSON 결과의 이중 언어화",
            "확장 가능한 멀티이펙터 선택기와 장치별 지원 상태 표시",
            "Tone Master Pro만 활성화하고 Neural DSP Quad Cortex 및 Line 6 Helix Family는 미구현 상태로 등록",
            "추가 장치 두 개를 나중에 이름 붙일 수 있는 예약 슬롯으로 유지",
            "EXE와 문서를 함께 제공하는 Windows 배포 ZIP 추가",
            "45초 제한을 제거하고 끝 시간 0/빈칸으로 전체 곡을 최대 20분까지 분석",
            "Demucs htdemucs_6s로 건반·베이스·드럼·보컬·기타 외 소리를 분리하고 guitar stem만 DSP 분석",
            "30초 단위 AI 분리로 5분 이상 긴 곡의 메모리 사용량 제한 및 조각별 진행 상태 표시",
            "로컬 파일이 없을 때 Windows PC 재생음(WASAPI loopback) 또는 오디오 입력을 임시 WAV로 녹음",
            "AI 분석 취소, 녹음 중지, 분리 모델 캐시 상태와 상세 오류 표시",
            "YouTube 자동 추출 대신 정상 브라우저 재생음을 녹음하는 입력 경로 제공",
        ],
        "changes_en": [
            "Added live Korean/English switching with language-specific UI fonts",
            "Uses Malgun Gothic for Korean and Arial Narrow for English",
            "Localized recipe explanations, errors, diagnostics, developer blocks, changelog, and HTML/JSON output",
            "Added an extensible multi-effects selector with per-device support status",
            "Tone Master Pro remains active; Neural DSP Quad Cortex and Line 6 Helix Family are listed as not implemented",
            "Kept two additional unnamed device slots for future units",
            "Added a Windows distribution ZIP containing the EXE and documentation",
            "Removed the 45-second limit; End 0/blank analyzes up to 20 minutes of the full item",
            "Uses Demucs htdemucs_6s to separate keys, bass, drums, vocals, and other sounds, then analyzes only the guitar stem",
            "Processes long tracks in 30-second AI chunks to bound memory and report per-chunk progress",
            "Records Windows PC playback (WASAPI loopback) or an audio input to a temporary WAV when no local file is available",
            "Added analysis cancellation, recording stop, model-cache diagnostics, and detailed separation errors",
            "Provides browser-playback recording instead of automated YouTube extraction",
        ],
        "known_issues": [
            "Tone Master Pro 외 장치는 선택 화면만 제공하며 분석 버튼이 비활성화됨",
            "장치별 카탈로그 구현에는 해당 제조사의 공식 매뉴얼·모델/파라미터 자료가 필요함",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
            "Demucs 6-stem의 guitar 출력은 실험적이므로 잔여 악기 누출과 인공음이 생길 수 있음",
            "AI 모델을 ZIP에 재배포하지 않아 첫 기타 분리 실행에는 인터넷 연결이 필요함",
            "CPU에서 5분 이상 곡 분리는 재생 시간보다 오래 걸릴 수 있음",
        ],
        "known_issues_en": [
            "Devices other than Tone Master Pro are selection placeholders and disable analysis",
            "Each new device catalog requires official manuals and model/parameter documentation",
            "This unsigned development build may trigger a Windows warning",
            "The Demucs 6-stem guitar output is experimental and may contain bleed or artifacts",
            "The AI weights are not redistributed in the ZIP, so the first guitar-isolation run needs internet access",
            "CPU separation of tracks over five minutes can take longer than real time",
        ],
    },
    {
        "version": "0.0.01",
        # 이전 릴리스 날짜가 다음 빌드의 BUILD_DATE 변경을 따라가지 않게 고정한다.
        "date": "2026-09-02",
        "status": "최초 비공개 프리뷰",
        "status_en": "Initial private preview",
        "changes": [
            "로컬 오디오 3~45초 구간의 스펙트럼·다이내믹·공간 특징 분석",
            "Tone Master Pro 펌웨어 1.8.58 / Model Guide Rev. J 기반 추천 3종",
            "픽업·풀믹스·출력 연결 방식에 따른 레시피 보정",
            "블록 순서, 실제 모델명, 노브 시작값과 추천 이유 표시",
            "JSON 데이터와 단일 HTML 분석 리포트 내보내기",
            "개발자 옵션: 처리 시퀀스 블록 다이어그램, 단계 로그, 클릭형 한글 코드 뷰어",
            "YouTube 주소는 출처 기록·브라우저 열기 전용이며 음원 다운로드는 제공하지 않음",
        ],
        "changes_en": [
            "Analyzes a 3–45 second local-audio segment for spectral, dynamic, and spatial features",
            "Provides three Tone Master Pro recipes for firmware 1.8.58 / Model Guide Rev. J",
            "Corrects recipes for pickup, full-mix influence, and output connection",
            "Shows block order, actual model names, knob starting values, and recommendation reasons",
            "Exports machine-readable JSON and a standalone HTML analysis report",
            "Developer options include a sequence diagram, live log, and clickable Korean-commented source viewer",
            "YouTube URLs are reference/browser shortcuts only; no audio download is provided",
        ],
        "known_issues": [
            "공개된 프리셋 쓰기 API가 없어 TMP/Pro Control에 값을 수동 적용해야 함",
            "기타 분리 모델이 없는 휴리스틱 프리뷰이므로 풀믹스의 분석 오차가 큼",
            "코드 서명 인증서가 없는 개발 빌드라 Windows가 실행 경고를 표시할 수 있음",
        ],
        "known_issues_en": [
            "No public preset-writing API is available, so values must be entered manually in TMP/Pro Control",
            "This heuristic preview has no guitar-separation model and is less accurate on full mixes",
            "This unsigned development build may trigger a Windows warning",
        ],
    }
]


TEMPLATES: list[dict] = [
    {
        "id": "blackface_clean",
        "name": "블랙패널 스튜디오 클린",
        "name_en": "Black-panel Studio Clean",
        "archetype": "클린",
        "archetype_en": "Clean",
        "description": "넓은 헤드룸, 단단한 저역과 또렷한 어택",
        "description_en": "Wide headroom, firm lows, and a clear attack",
        "target": {"saturation": 0.10, "brightness": 0.62, "body": 0.48, "compression": 0.22, "ambience": 0.20, "modulation": 0.05},
        "amp": "Fender '65 Twin Reverb",
        "cab": "Fender 2x12 '65 Twin C12K",
        "mic": "Condenser C414",
        "mic_position": "Cone edge / 1.0 in / off-axis",
        "drive": None,
        "mod": None,
        "delay": None,
        "reverb": "'65 Spring Reverb",
        "tags": ["pop", "funk", "country", "pedal platform"],
    },
    {
        "id": "jc_wide_clean",
        "name": "와이드 솔리드스테이트 클린",
        "name_en": "Wide Solid-state Clean",
        "archetype": "클린/코러스",
        "archetype_en": "Clean / Chorus",
        "description": "초고해상도 클린과 넓은 스테레오 코러스",
        "description_en": "Detailed clean tone with wide stereo chorus",
        "target": {"saturation": 0.08, "brightness": 0.70, "body": 0.36, "compression": 0.18, "ambience": 0.28, "modulation": 0.62},
        "amp": "JC Clean",
        "cab": "2x12 JC",
        "mic": "Dynamic MD421",
        "mic_position": "Cone / 2.0 in / off-axis",
        "drive": None,
        "mod": "Chorus Stereo",
        "delay": None,
        "reverb": "Small Hall Reverb",
        "tags": ["80s", "city pop", "ambient", "clean"],
    },
    {
        "id": "deluxe_edge",
        "name": "스무스 디럭스 엣지",
        "name_en": "Smooth Deluxe Edge",
        "archetype": "엣지 오브 브레이크업",
        "archetype_en": "Edge of Breakup",
        "description": "픽킹에 따라 클린과 가벼운 드라이브를 오가는 톤",
        "description_en": "Moves between clean and light drive with picking dynamics",
        "target": {"saturation": 0.28, "brightness": 0.55, "body": 0.48, "compression": 0.34, "ambience": 0.24, "modulation": 0.06},
        "amp": "Fender '65 Deluxe Reverb Blonde NBC",
        "cab": "Fender 1x12 '65 Deluxe C12K",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 1.0 in / on-axis",
        "drive": "Lightyear",
        "mod": None,
        "delay": None,
        "reverb": "'65 Spring Reverb",
        "tags": ["indie", "pop", "roots", "edge"],
    },
    {
        "id": "bassman_blues",
        "name": "트위드 블루스 드라이브",
        "name_en": "Tweed Blues Drive",
        "archetype": "블루스 드라이브",
        "archetype_en": "Blues Drive",
        "description": "따뜻한 중저역과 손끝 반응이 살아 있는 블루스 톤",
        "description_en": "Warm low mids and touch-responsive blues drive",
        "target": {"saturation": 0.42, "brightness": 0.42, "body": 0.62, "compression": 0.42, "ambience": 0.16, "modulation": 0.04},
        "amp": "Fender '59 Bassman Custom",
        "cab": "Fender 4x10 '59 Bassman Greenback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 2.0 in / off-axis",
        "drive": "Blues Maker",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["blues", "roots", "classic"],
    },
    {
        "id": "class_a_chime",
        "name": "클래스 A 차임 크런치",
        "name_en": "Class-A Chime Crunch",
        "archetype": "차임/크런치",
        "archetype_en": "Chime / Crunch",
        "description": "상단의 차임과 개방감 있는 자연스러운 브레이크업",
        "description_en": "Chiming highs with open, natural breakup",
        "target": {"saturation": 0.40, "brightness": 0.72, "body": 0.42, "compression": 0.34, "ambience": 0.22, "modulation": 0.10},
        "amp": "UK 30 Brilliant",
        "cab": "2x12 UK30 Alnico Blue",
        "mic": "Dynamic SM57",
        "mic_position": "Cone edge / 1.0 in / off-axis",
        "drive": "Mythic Drive",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["brit pop", "indie", "jangle", "classic rock"],
    },
    {
        "id": "plexi_crunch",
        "name": "빈티지 브리티시 크런치",
        "name_en": "Vintage British Crunch",
        "archetype": "크런치",
        "archetype_en": "Crunch",
        "description": "다이내믹한 어택과 풍부한 배음의 클래식 록 톤",
        "description_en": "Classic-rock tone with dynamic attack and rich harmonics",
        "target": {"saturation": 0.54, "brightness": 0.56, "body": 0.55, "compression": 0.44, "ambience": 0.12, "modulation": 0.04},
        "amp": "British Plexi",
        "cab": "4x12 British Greenback",
        "mic": "Dynamic SM57",
        "mic_position": "Cone edge / 0.5 in / on-axis",
        "drive": None,
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["classic rock", "rhythm", "70s"],
    },
    {
        "id": "british_800",
        "name": "80년대 브리티시 하드록",
        "name_en": "80s British Hard Rock",
        "archetype": "하드록",
        "archetype_en": "Hard Rock",
        "description": "공격적인 미드와 즉각적인 어택의 리듬 톤",
        "description_en": "Rhythm tone with aggressive mids and immediate attack",
        "target": {"saturation": 0.66, "brightness": 0.60, "body": 0.50, "compression": 0.58, "ambience": 0.12, "modulation": 0.05},
        "amp": "British 800",
        "cab": "4x12 British G12H",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Greenbox 8",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["80s", "hard rock", "punk", "rhythm"],
    },
    {
        "id": "jubilee_lead",
        "name": "브리티시 싱잉 리드",
        "name_en": "British Singing Lead",
        "archetype": "리드",
        "archetype_en": "Lead",
        "description": "집중된 미드와 매끄러운 서스테인의 솔로 톤",
        "description_en": "Focused mids and smooth sustain for melodic solos",
        "target": {"saturation": 0.70, "brightness": 0.52, "body": 0.52, "compression": 0.66, "ambience": 0.32, "modulation": 0.08},
        "amp": "British Jubilee Lead",
        "cab": "4x12 British Jubilee V30",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 1.0 in / on-axis",
        "drive": "Mythic Drive II",
        "mod": None,
        "delay": "Analog Delay",
        "reverb": "Large Plate Reverb",
        "tags": ["lead", "solo", "hard rock"],
    },
    {
        "id": "solo_lead",
        "name": "핫로드 서스테인 리드",
        "name_en": "Hot-rodded Sustain Lead",
        "archetype": "리드/하이게인",
        "archetype_en": "Lead / High Gain",
        "description": "타이트한 어택과 유연한 서스테인의 현대 리드",
        "description_en": "Modern lead with tight attack and fluid sustain",
        "target": {"saturation": 0.76, "brightness": 0.55, "body": 0.46, "compression": 0.70, "ambience": 0.34, "modulation": 0.06},
        "amp": "Solo 100 Overdrive",
        "cab": "4x12 Solo G12H",
        "mic": "Dynamic MD421",
        "mic_position": "Cap edge / 1.0 in / off-axis",
        "drive": "Greenbox 10",
        "mod": None,
        "delay": "Digital Delay",
        "reverb": "Large Plate Reverb",
        "tags": ["lead", "modern rock", "fusion"],
    },
    {
        "id": "evh_blue",
        "name": "타이트 모던 크런치",
        "name_en": "Tight Modern Crunch",
        "archetype": "모던 하드록",
        "archetype_en": "Modern Hard Rock",
        "description": "포화감은 높지만 음 분리가 선명한 블루 채널 톤",
        "description_en": "A saturated blue-channel tone with clear note separation",
        "target": {"saturation": 0.73, "brightness": 0.60, "body": 0.48, "compression": 0.65, "ambience": 0.10, "modulation": 0.04},
        "amp": "EVH 5150IIIS 6L6 Blue",
        "cab": "4x12 EVH 5150IIIS",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Integrator Boost",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["modern rock", "metal", "riff"],
    },
    {
        "id": "evh_red",
        "name": "5150 모던 하이게인",
        "name_en": "5150 Modern High Gain",
        "archetype": "하이게인",
        "archetype_en": "High Gain",
        "description": "강한 포화와 타이트한 저역의 현대 메탈 톤",
        "description_en": "Modern metal tone with heavy saturation and tight lows",
        "target": {"saturation": 0.88, "brightness": 0.58, "body": 0.50, "compression": 0.82, "ambience": 0.08, "modulation": 0.02},
        "amp": "EVH 5150IIIS 6L6 Red",
        "cab": "4x12 EVH 5150IIIS",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Grunt Boost",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["metal", "djent", "high gain", "riff"],
    },
    {
        "id": "double_wreck",
        "name": "아메리칸 대형 하이게인",
        "name_en": "Large American High Gain",
        "archetype": "하이게인",
        "archetype_en": "High Gain",
        "description": "큰 저역과 공격적인 질감의 현대 헤비 톤",
        "description_en": "Modern heavy tone with massive lows and aggressive texture",
        "target": {"saturation": 0.86, "brightness": 0.46, "body": 0.68, "compression": 0.80, "ambience": 0.08, "modulation": 0.02},
        "amp": "Double Wreck",
        "cab": "4x12 Mega V30",
        "mic": "Dynamic MD421",
        "mic_position": "Cap edge / 0.5 in / off-axis",
        "drive": "Greenbox 10",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["metal", "drop tuning", "heavy"],
    },
    {
        "id": "petrol_tight",
        "name": "포커스드 메탈 리듬",
        "name_en": "Focused Metal Rhythm",
        "archetype": "타이트 하이게인",
        "archetype_en": "Tight High Gain",
        "description": "팜뮤트 정의감과 집중된 미드가 우선인 리듬 톤",
        "description_en": "Rhythm tone prioritizing palm-mute definition and focused mids",
        "target": {"saturation": 0.82, "brightness": 0.64, "body": 0.42, "compression": 0.76, "ambience": 0.06, "modulation": 0.02},
        "amp": "Petrol",
        "cab": "4x12 Petrol V30",
        "mic": "Dynamic SM57",
        "mic_position": "Cap edge / 0.0 in / off-axis",
        "drive": "Integrator Boost",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["metal", "tight", "rhythm"],
    },
    {
        "id": "vintage_fuzz",
        "name": "빈티지 게르마늄 퍼즈",
        "name_en": "Vintage Germanium Fuzz",
        "archetype": "퍼즈",
        "archetype_en": "Fuzz",
        "description": "볼륨 반응이 좋고 따뜻하게 뭉치는 올드스쿨 퍼즈",
        "description_en": "Warm old-school fuzz with responsive volume cleanup",
        "target": {"saturation": 0.80, "brightness": 0.40, "body": 0.58, "compression": 0.72, "ambience": 0.10, "modulation": 0.03},
        "amp": "British 45",
        "cab": "4x12 British Greenback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 2.0 in / off-axis",
        "drive": "Round Fuzz (Germanium)",
        "mod": None,
        "delay": None,
        "reverb": "Small Room Reverb",
        "tags": ["60s", "psychedelic", "vintage fuzz"],
    },
    {
        "id": "wall_fuzz",
        "name": "빅 월 퍼즈",
        "name_en": "Big Wall Fuzz",
        "archetype": "퍼즈",
        "archetype_en": "Fuzz",
        "description": "두꺼운 서스테인과 넓게 퍼지는 벽 같은 퍼즈",
        "description_en": "Thick sustain and a wide wall-of-sound fuzz texture",
        "target": {"saturation": 0.94, "brightness": 0.45, "body": 0.72, "compression": 0.90, "ambience": 0.22, "modulation": 0.04},
        "amp": "Fender '65 Twin Reverb",
        "cab": "Fender 2x12 '65 Twin Creamback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 1.0 in / off-axis",
        "drive": "Big Apple Fuzz",
        "mod": None,
        "delay": None,
        "reverb": "Large Plate Reverb",
        "tags": ["alternative", "shoegaze", "wall of sound", "fuzz"],
    },
    {
        "id": "ambient_clean",
        "name": "스테레오 앰비언트 클린",
        "name_en": "Stereo Ambient Clean",
        "archetype": "앰비언트",
        "archetype_en": "Ambient",
        "description": "넓은 모듈레이션, 긴 딜레이와 홀 리버브의 공간계 톤",
        "description_en": "Wide modulation, long delay, and spacious hall reverb",
        "target": {"saturation": 0.12, "brightness": 0.64, "body": 0.38, "compression": 0.36, "ambience": 0.88, "modulation": 0.58},
        "amp": "JC Clean",
        "cab": "2x12 JC",
        "mic": "Condenser C414",
        "mic_position": "Cone / 3.0 in / off-axis",
        "drive": None,
        "mod": "Chorus Stereo",
        "delay": "Stereo Memory Delay",
        "reverb": "Modulated Large Hall Reverb",
        "tags": ["ambient", "post rock", "worship", "soundscape"],
    },
    {
        "id": "shoegaze_fuzz",
        "name": "앰비언트 퍼즈 레이어",
        "name_en": "Ambient Fuzz Layer",
        "archetype": "퍼즈/앰비언트",
        "archetype_en": "Fuzz / Ambient",
        "description": "두꺼운 퍼즈 뒤에 넓고 긴 공간계를 쌓는 레이어 톤",
        "description_en": "Thick fuzz layered beneath wide, long ambience",
        "target": {"saturation": 0.86, "brightness": 0.52, "body": 0.64, "compression": 0.86, "ambience": 0.78, "modulation": 0.38},
        "amp": "Fender '65 Twin Reverb",
        "cab": "Fender 2x12 '65 Twin Creamback",
        "mic": "Ribbon R121",
        "mic_position": "Cone edge / 2.0 in / off-axis",
        "drive": "Big Apple Fuzz",
        "mod": "Chorus Stereo",
        "delay": "Stereo Memory Delay",
        "reverb": "Large Hall Reverb",
        "tags": ["shoegaze", "post rock", "ambient", "fuzz"],
    },
    {
        "id": "rockbox_direct",
        "name": "80년대 다이렉트 레코딩",
        "name_en": "80s Direct Recording",
        "archetype": "폴리시드/다이렉트",
        "archetype_en": "Polished / Direct",
        "description": "압축된 앰프 톤과 코러스·에코를 한 블록으로 구성",
        "description_en": "Compressed amp tone, chorus, and echo in a single block",
        "target": {"saturation": 0.52, "brightness": 0.58, "body": 0.42, "compression": 0.78, "ambience": 0.56, "modulation": 0.62},
        "amp": None,
        "cab": None,
        "mic": None,
        "mic_position": None,
        "drive": "Rockbox 100",
        "mod": None,
        "delay": None,
        "reverb": "Small Plate Reverb",
        "tags": ["80s", "direct", "studio", "chorus"],
    },
]


KNOWN_MODELS = {
    "amps": sorted({t["amp"] for t in TEMPLATES if t["amp"]}),
    "cabinets": sorted({t["cab"] for t in TEMPLATES if t["cab"]}),
    "effects": sorted(
        {
            item
            for t in TEMPLATES
            for item in (t["drive"], t["mod"], t["delay"], t["reverb"])
            if item
        }
        | {
            "Pedal Comp",
            "Simple Compressor",
            "Metal Gate",
            "Noise Gate",
            "EQ-5 Parametric",
            "Low/High Cut Filter",
        }
    ),
    "microphones": [
        "Dynamic MD421",
        "Dynamic RE20",
        "Dynamic SM57",
        "Dynamic SM7B",
        "Ribbon R121",
        "Condenser C414",
        "Condenser M23",
    ],
}
